name:                bigquery-sql-parser
version:             0.1.0.0
github:              "ollimandoliini/bigquery-sql-parser"
license:             BSD3
author:              "Olli Kortelahti"
maintainer:          "olli@olli.com"
copyright:           "2022 Olli Kortelahti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ollimandoliini/bigquery-sql-parser#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- containers
- raw-strings-qq

library:
  source-dirs: src

executables:
  bigquery-sql-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bigquery-sql-parser

tests:
  bigquery-sql-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bigquery-sql-parser
    - QuickCheck
